

name: "baseline_transformer_spm_factor_sign"
#model_dir: "model_filtered/baseline_transformer_spm_factor_sign"
data:
    train: "data_filtered/train"  # Path to training data
    dev: "data_filtered/dev"      # Path to dev data
    test: "data_filtered/test"    # Path to test data
    src: "symbol.txt"
    trg: "sentences.spm.txt"
    factors: ["factor.x.txt","factor.y.txt"]
    level: "word"
    lowercase: False
    max_sent_length: 500
    factor_voc_limit: 10000
    factor_voc_min_freq: 1
    use_factor: True
    
testing:
    beam_size: 5
    alpha: 1.0
    eval_metrics: "bleu"
    postprocess: False

training:
    random_seed: 42
    optimizer: "adam"
    normalization: "tokens"
    adam_betas: [0.9, 0.999]
    scheduling: "plateau"
    patience: 7
    decrease_factor: 0.7
    loss: "crossentropy"
    learning_rate: 0.0001
    learning_rate_min: 0.00000001
    weight_decay: 0.0
    label_smoothing: 0.2
    batch_size: 64
    eval_batch_size: 64
    batch_multiplier: 1
    early_stopping_metric: "eval_metric"
    epochs: 300
    validation_freq: 424
    logging_freq: 100
    eval_metric: "bleu"
    overwrite: True
    shuffle: True
    use_cuda: True
    max_output_length: 200
    print_valid_sents: [0, 1, 2, 3, 6]
    keep_last_ckpts: 1
    model_dir: "model_filtered/baseline_transformer_spm_factor_sign"

model:
    initializer: "xavier"
    bias_initializer: "zeros"
    init_gain: 1.0
    embed_initializer: "xavier"
    embed_init_gain: 1.0
    encoder:
        type: "transformer"
        num_layers: 6
        num_heads: 8
        embeddings:
            embedding_dim: 464
            scale: True
            dropout: 0.
        # changes for factors:
        factor_embeddings:
            embedding_dim: 24
            scale: False
        factor_combine: "concatenate"
        # typically ff_size = 4 x hidden_size
        hidden_size: 512
        ff_size: 2048
        dropout: 0.1
    decoder:
        type: "transformer"
        num_layers: 6
        num_heads: 8
        embeddings:
            embedding_dim: 512
            scale: True
            dropout: 0.
        # typically ff_size = 4 x hidden_size
        hidden_size: 512
        ff_size: 2048
        dropout: 0.1

    